### PR TITLE
Add Postman resources to test the REST API

### PR DESCRIPTION
**Pull request by virtualtam**
See:
- https://www.getpostman.com/
- https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables
- https://www.getpostman.com/docs/v6/postman/scripts/pre_request_scripts
- https://www.getpostman.com/docs/v6/postman/environments_and_globals/intro_to_environments_and_globals
- https://developer.dansksupermarked.dk/v1/api/guides/jwt-authentication-in-postman/
- https://gist.github.com/corbanb/db03150abbe899285d6a86cc480f674d
- https://www.jonathan-petitcolas.com/2014/11/27/creating-json-web-token-in-javascript.html
- https://github.com/brix/crypto-js

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Postman doesn't really work on my desktop (the window becomes black after a few clicks), but from what I could see it seems to work fine. :+1:

**Review by ArthurHoaro — APPROVED** [review]

**Comment by virtualtam** [comment]
Weird, how did you install it? I'm using Postman on Arch (via [AUR](https://aur.archlinux.org/packages/postman-bin/)) and Ubuntu Xenial and Bionic (via [ansible-role-postman](https://github.com/gantsign/ansible-role-postman)) without any issue.

**Comment by ArthurHoaro** [comment]
I'm using Arch (anarchy) with KDE and installed it with AUR. Maybe it's an issue with the dark theme. To be fair I didn't look into the issue at all.

**Comment by nodiscc** [comment]
Is postman closed source?

absolutelyproprietary

**Comment by virtualtam** [comment]
Not open source indeed, but it is free to use and widely adopted by hordes of web developers :)

Some alternatives:
- [Insomnia](https://insomnia.rest/)
- [HTTPie](https://httpie.org/)
-  [httplive](https://github.com/gencebay/httplive)

**Pull request merged**
